lib/learnathon/web/router.ex
defmodule Learnathon.Web.Router do
  use Learnathon.Web, :router
  use Phoenix.Router

  if Mix.env == :dev do
    forward "/sent_emails", Bamboo.EmailPreviewPlug
  end

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Learnathon.Auth, repo: Learnathon.Repo
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Learnathon.Web do
    pipe_through :browser

    get "/skill_level_and_interests", SurveyController, :show
    get "/submission", SubmissionController, :confirm
    post "/submission", SubmissionController, :create
    put "/submission", SubmissionController, :update

    resources "/sessions", SessionController, only: [:new, :create, :delete]

    get "/", PageController, :index
  end

  scope "/", Learnathon.Web do
    pipe_through [:browser, :authenticate_person]
    resources "/people", PersonController, only: [:index, :show, :new, :create]
  end

  # Other scopes may use custom stacks.
  # scope "/api", Learnathon.Web do
  #   pipe_through :api
  # end
end

lib/learnathon/web/controllers/fallback_controller.ex
defmodule Learnathon.Web.FallbackController do
  @moduledoc """
  Translates controller action results into valid `Plug.Conn` responses.

  See `Phoenix.Controller.action_fallback/1` for more details.
  """
  use Learnathon.Web, :controller

  def call(conn, {:errors, %Ecto.Changeset{} = changeset}) do
    conn
    |> put_flash(:errors, changeset.errors)
    |> redirect(to: person_path(conn, :index))
  end

  def call(conn, {:error, %Ecto.Changeset{} = changeset}) do
    conn
    |> put_flash(:errors, changeset.errors)
    |> redirect(to: person_path(conn, :new))
  end

  def call(conn, {:error, :not_found}) do
    conn
    |> put_status(:not_found)
    |> render(Learnathon.Web.ErrorView, :"404")
  end

  def call(conn, {:error, message}) do
    conn
    |> put_flash(:error, message)
    |> redirect(to: page_path(conn, :index))
  end

end

lib/learnathon/web/controllers/page_controller.ex
defmodule Learnathon.Web.PageController do
  use Learnathon.Web, :controller

  def index(conn, _params) do
    render conn, "index.html"
  end

  def submission(conn, %{"workshop_submission" => workshop_submission}) do
    render conn, "thank_you.html", workshop_submission: workshop_submission
  end
end

lib/learnathon/web/controllers/person_controller.ex
defmodule Learnathon.Web.PersonController do
  use Learnathon.Web, :controller
  alias Learnathon.{SubmissionManager, SubmissionManager.Person}

  action_fallback Learnathon.Web.FallbackController
  plug :authenticate_person when action in [:index, :show, :update, :create, 
                                            :delete, :new]

  def new(conn, _params) do
    changeset = SubmissionManager.person_changeset(%Person{})
    conn |> render("new.html", changeset: changeset)
  end

  def index(conn, _params) do
    people = Repo.all(Learnathon.SubmissionManager.Person)
    render conn, "index.html", people: people
  end

  def show(conn, %{"id" => id}) do
    with {:ok, person} <- Learnathon.SubmissionManager.fetch_person(id) do
      conn |> render("show.html", person: person)
    end
  end

  def create(conn, %{"person" => person_params}) do
    with {:ok, person} <- SubmissionManager.register_person(person_params) do
      conn
      |> Learnathon.Auth.login(person)
      |> put_flash(:info, "#{person.name} created!")
      |> redirect(to: person_path(conn, :index))
    end
  end

end

lib/learnathon/web/controllers/session_controller.ex
defmodule Learnathon.Web.SessionController do
  use Learnathon.Web, :controller
  alias Learnathon.Repo

  def new(conn, _) do
    render conn, "new.html"
  end

  def create(conn, %{"session" => %{"email" => email, "password" => pw}}) do
    case Learnathon.Auth.login_by_email_and_pass(conn, email, pw, repo: Repo) do
      {:ok, conn} -> 
        conn
        |> put_flash(:info, "Welcome back!")
        |> redirect(to: page_path(conn, :index))
      {:error, _reason, conn} -> 
        conn
        |> put_flash(:error, "Invalid email and/or password combo.")
        |> render("new.html")
    end
  end

  def delete(conn, _) do
    conn
    |> Learnathon.Auth.logout()
    |> redirect(to: page_path(conn, :index))
  end
end

lib/learnathon/web/controllers/submission_controller.ex
defmodule Learnathon.Web.SubmissionController do
  use Learnathon.Web, :controller

  alias Learnathon.{
          SubmissionManager,
          SubmissionManager.Person,
          SubmissionManager.ConfirmationCode,
          Email, 
          Mailer 
        }

  import SubmissionManager, only: [
                                    get_or_create_person: 1,
                                    create_person_confirmation: 1,
                                    get_confirmation_code: 1,
                                    confirm_person: 1,
                                  ]

  action_fallback Learnathon.Web.FallbackController
  plug :scrub_params, "submission" when action in [:create]

  def create(conn, %{"submission" => submission}) do

    changeset = SubmissionManager.person_changeset(%Person{}, submission)
    with {:ok, %Person{} = person} <- get_or_create_person(submission),
         {:ok, %ConfirmationCode{} = confirmation}
         <- create_person_confirmation(person) do

      email_confirmation(conn, person, confirmation)

      conn
      |> put_flash(:info, "Check your email for a confirmation message.")
      |> redirect(to: page_path(conn, :index))
    end

  end

  def confirm(conn, params) do
    with {:ok, params} <- validate_confirmation_params(params) do
      update conn, %{"confirmation_code" => params["submission"]}
    end
  end

  def update(conn, %{"confirmation_code" => confirmation_code}) do
    with {:ok, confirmation_code} <- get_confirmation_code(confirmation_code),
         {:ok, person} <- confirm_person(confirmation_code) do

      email_thank_you(person)

      conn
      |> put_flash(:info, "You have been confirmed! Thank you!")
      |> redirect(to: page_path(conn, :index))
    end
  end

  defp validate_confirmation_params(params) do
    if (String.length(params["submission"]) == 64) do
      {:ok, params}
    else
      {:error, "🕵️‍ confirmation code invalid, cut the bologney! 🕵️‍"}
    end
  end

  defp email_thank_you(person) do
    Email.confirmation_success(person)
    # |> Mailer.deliver_now
  end

  defp email_confirmation(conn, person, confirmation) do
    Email.confirmation_email(person, confirmation, conn)
    # |> Mailer.deliver_later
  end

end

lib/learnathon/web/controllers/survey_controller.ex
defmodule Learnathon.Web.SurveyController do
  use Learnathon.Web, :controller
  action_fallback Learnathon.Web.FallbackController

  def show(conn) do
    # case conn.request_path do

  end
end

lib/learnathon/web/views/email_view.ex
defmodule Learnathon.EmailView do
  use Learnathon.Web, :view

end

lib/learnathon/web/views/error_view.ex
defmodule Learnathon.Web.ErrorView do
  use Learnathon.Web, :view

  def render("404.html", _assigns) do
    "Page not found"
  end

  def render("500.html", _assigns) do
    "Internal server error"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render "500.html", assigns
  end
end

lib/learnathon/web/views/layout_view.ex
defmodule Learnathon.Web.LayoutView do
  use Learnathon.Web, :view

  def show_flash(conn) do
    Phoenix.Controller.get_flash(conn) |> flash_msg
  end

  def flash_msg(%{"info" => msg}) do
    ~E"<div class='alert alert-info-text text-center'><%= msg %></div>"
  end

  def flash_msg(%{"error" => msg}) do
    ~E"<div class='alert alert-danger-text text-center'><%= msg %></div>"
  end

  def flash_msg(%{"errors" => errors}) do
    Enum.map(errors, fn({k, v}) -> 
      {msg, _} = v
      ~E"<ul class='alert alert-danger-text text-center p-0 m-0'>
           <%= k %> <%= msg %>
         </ul>"
    end)
  end

  def flash_msg(_) do
    nil
  end
end

lib/learnathon/web/views/page_view.ex
defmodule Learnathon.Web.PageView do
  use Learnathon.Web, :view
end

lib/learnathon/web/views/person_view.ex
defmodule Learnathon.Web.PersonView do
  use Learnathon.Web, :view

  alias Learnathon.SubmissionManager.Person

  def first_name(%Person{name: name}) do
    name
    |> String.split(" ")
    |> Enum.at(0)
  end
end

lib/learnathon/web/views/session_view.ex
defmodule Learnathon.Web.SessionView do
  use Learnathon.Web, :view
end

lib/learnathon/web/views/speaker_view.ex
defmodule Learnathon.Web.SpeakerView do
  use Learnathon.Web, :view
end

lib/learnathon/web/views/submission_view.ex
defmodule Learnathon.Web.SubmissionView do
  use Learnathon.Web, :view
end

lib/learnathon/web/templates/confirmation.html.eex
<h3>
  <a href="<%= submission_url(@conn, :confirm) %>?submission=<%= @cc %>">
    Please confirm your email address for learnathon.nyc!
  </a>
</h3>

lib/learnathon/web/templates/confirmation_plain.html.eex
Confirm by copying and pasting the link from here into your browser
<%= submission_url(@conn, :confirm) %>?submission=<%= @cc %>

lib/learnathon/web/templates/confirmation_success.html.eex
<h1>Thanks for confirming your email!</h1>
<p>We will send an update in April.</p>

lib/learnathon/web/templates/confirmation_success_plain.html.eex
Confirm by copying and pasting the link from here into your browser https://learnathon.nyc/confirm?p=redlwjnfflwkjnfqwlkjfnqjwhfebqwjkfhb

lib/learnathon/web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Learnathon.nyc</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
    <style>
      /* note: this is a hack for ios iframe for bootstrap themes shopify page */
      /* this chunk of css is not part of the toolkit :) */
      /* …curses ios, etc… */
      @media (max-width: 768px) and (-webkit-min-device-pixel-ratio: 2) {
        body {
          width: 1px;
          min-width: 100%;
          *width: 100%;
        }
        #stage {
          height: 1px;
          overflow: auto;
          min-height: 100vh;
          -webkit-overflow-scrolling: touch;
        }
      }
    </style>

  </head>

  <body>
    <nav class="navbar fixed-top navbar-light bg-faded mb-0">
      <div class="container">
        <div class="row">
          <div class="brand col">
            <a class="navbar-brand" href="#">Learnathon.nyc</a>
          </div>
          <div class="link-items col pt-2">
            <ul class="list-inline float-right">
              <li><a href="#speakers">Speakers</a></li>
              <li><a href="#schedule">Schedule</a></li>
              <li><a href="#hackathon">Hackathon</a></li>
              <li><a href="#tickets">Tickets</a></li>
            </ul>
          </div>
        </div>
      </div>
    </nav>

    <%= if @current_person do %>
      <div class="header">
        <ol class="breadcrumb text-right">
          <li><%= @current_person.email %></li>
          <li><%= link "Log Out", 
                  to: session_path(@conn, :delete, @current_person), 
                  method: "delete" %>
          </li>
        </ol>
      </div>
    <% end %>
    <div class="container">

      <%= show_flash(@conn) %>

      <main role="main">
      <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/learnathon/web/templates/page/app_block_flatiron.html.eex
<div class="block block-inverse block-transparent py-0 app-block-flatiron">

  <div class="block-bg-clip">
    <div class="block-bg">
      <div class="block-bg-img"></div>
    </div>
  </div>

  <div class="container" id="grid">
    <div class="row">
      <div class="col-lg-4 col-md-6">
        <div class="row mb-3 mb-md-5">
          <div class="col-lg-12">
            <div class="card card-bold card-danger mb-0 app-box-shadow">
              <img class="w-100" src="images/flatiron-school-2.jpg">
              <div class="card-block pb-5">
                <h4 class="mb-0">FLATIRON SCHOOL</h4>
                <p class="text-serif"><em>280 person capacity</em></p>
                <hr>
                <p class="text-serif"><em>Thank you to Flatiron school for 
                  donating your space.</em></p>

                <p class="text-serif"><em>(The organizers of this event do not work for Flatiron. We are graduates.)</em></p>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="col-lg-8 col-md-6">
        <div class="row">
          <div class="col mb-3 mb-md-5 hidden-md-down">
            <div class="app-box-shadow">
              <img src="images/flatiron-logo.png">
            </div>
          </div>
          <div class="col">
            <img class="w-100" src="images/flatiron-workshop-cropped.png">
          </div>
        </div>
        <div class="row">
          <div class="col-lg-12">
            <img class="w-100" src="images/flatiron-turing-facing-out.png">
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

lib/learnathon/web/templates/page/app_block_liberty.html.eex
<div class="block block-fill-height app-block-liberty"
     style="background-image: url(/images/statue-of-liberty.png)">

  <div class="block-sm-middle block-xs-bottom">
    <div class="container">
      <div class="row">
        <div class="col-lg-5">
          <h1 class="block-title mb-4">
            <span class="text-ribbon text-ribbon-primary">
              <span>
                <%= gettext "%{name}",
name: "NYC Learnathon Summer 2017" %>
              </span>
            </span>
          </h1>
          <p class="lead mt-1">
          <span class="text-ribbon text-ribbon-primary">
            <span>
              Join us for a weekend of talks and programming.
              <a href="#pricing" class="btn btn-secondary">
                Get your tickets
              </a>
            </span>
          </span>
          </p>
        </div>
      </div>
    </div>
  </div>
</div>

lib/learnathon/web/templates/page/app_block_live_streaming.html.eex
<div class="block block-transparent block-inverse block-angle app-block-live-streamingpl-1">
  <div class="block-bg-clip">
    <div class="block-bg">
      <div class="block-bg-img block-bg-img-top"
           style="background-image: url(images/madison-park.png)">
      </div>
    </div>
  </div>

  <div class="block-md-middle">
    <div class="container p-0 m-0">
      <div class="row live-streaming-row">
        <div class="col-lg-5">
          <h1 class="block-title mb-4">
            <span class="text-ribbon text-ribbon-secondary">
              <span>Live Streaming of Workshops</span>
            </span>
          </h1>
          <p class="lead">
          <span class="text-ribbon">
            <span>
              No matter where you are you can join us for workshops! 
            </span>
          </span>
          </p>
        </div>
      </div>
      <div class="row mb-3">
        <div class="col-8 p-0 m-0">
          <div class="w-100">
            <iframe class="live-streaming-iframe" src="https://www.youtube.com/embed/_2qkava0u9I" frameborder="0" allowfullscreen></iframe>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

lib/learnathon/web/templates/page/app_block_schedule.html.eex
<div id="schedule" class="block block-inverse block-fill-height app-block-schedule">
  <h3>Schedule</h3>
  <h4>Day One</h4>
  <table class="table table-inverse">
    <thead>
      <tr>
        <th>Time</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <th scope="row">12:00pm - 12:30pm</th>
        <td>Arrive and Mingle</td>
      </tr>
      <tr>
        <th scope="row">12:30pm - 12:45pm</th>
        <td>Enter Room and Find a seat.</td>
      </tr>
      <tr>
        <th scope="row">12:45pm - 1:00pm</th>
        <td>Opening Speech</td>
      </tr>
      <tr>
        <th scope="row">1:00pm - 1:45pm</th>
        <td>Melissa</td>
      </tr>
      <tr>
        <th scope="row">1:45 - 2:00pm</th>
        <td>Break</td>
      </tr>
      <tr>
        <th scope="row">2:00pm - 2:30pm</th>
        <td>Darie</td>
      </tr>
      <tr>
        <th scope="row">2:30pm - 3:00pm</th>
        <td>Pizza</td>
      </tr>
      <tr>
        <th scope="row">3:00pm - 3:30pm</th>
        <td>Avi</td>
      </tr>
      <tr>
        <th scope="row">3:30pm - 3:45pm</th>
        <td>Break</td>
      </tr>
      <tr>
        <th scope="row">3:45pm - 4:15pm</th>
        <td>Yianna</td>
      </tr>
      <tr>
        <th scope="row">4:15pm - 4:30pm</th>
        <td>Closing Ceremony</td>
      </tr>
      <tr>
        <th scope="row">4:30pm - 5:00pm</th>
        <td>More Mingling and end of Day 1</td>
      </tr>
    </tbody>
  </table>

  <h4>Day Two</h4>
  <table class="table table-inverse">
    <thead>
      <tr>
        <th>Time</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <th scope="row">12:00pm - 12:45pm</th>
        <td>Mirabai Talk</td>
      </tr>
      <tr>
        <th scope="row">12:45pm - 1:15pm</th>
        <td>Break up into groups</td>
      </tr>
      <tr>
        <th scope="row">1:15pm - 5:00pm</th>
        <td>Build</td>
      </tr>
    </tbody>
  </table>

</div>

lib/learnathon/web/templates/page/app_block_stay_up_to_date.html.eex
<div class="block block-transparent block-fill-height block-angle app-block-stay-up-to-date">
  <div class="block-bg-clip">
    <div class="block-bg">
      <div class="block-bg-img block-bg-img-top"
           style="background-image: url('images/west-side-highway.png')">
      </div>
    </div>
  </div>

  <div id="subscribe" class="block-xs-middle">
    <div class="container">
      <div class="row">
        <div class="col-md-6 offset-md-6">
          <h1 class="block-title mb-4">
            <span class="text-ribbon text-ribbon-primary">
              <span>Stay up to date with us.</span>
            </span>
          </h1>

          <div class="text-ribbon-inputs-split">
            <%= form_for @conn, submission_path(@conn, :create), 
                [as: :submission], fn form -> %>
              <%= text_input form, :name, 
                  [class: "form-control-lg h4 text-ribbon-input text-ribbon-primary",
                  placeholder: "Name"] %>
              <%= email_input form, :email, 
                  [class: "form-control-lg h4 text-ribbon-input text-ribbon-primary",
                  placeholder: "Email"] %>
              <%= submit "Stay up to date!", 
                  [class: "btn btn-primary btn-square btn-lg btn-block"] %>
            <% end %>
          </div>

        </div>
      </div>
    </div>
  </div>
</div>

lib/learnathon/web/templates/page/app_block_stenohack.html.eex
<div id="hackathon" class="block block-inverse block-fill-height app-block-hackathon">
  <h2>StenoHack at Learnathon.nyc Sunday 6/25 Hack Your Typing</h2>
  <p>We are starting with a talk by Mirabai Knight where you will learn how she types 260wpm. After the talk, when you're inspired to hack your typing, you will build your own steno typing tutor in any language and stack of your choice. We are asking that your program should work with 1 to 3-key chords and be as fun and addictive as possible.</p> 

  <p>Other guidelines:</p>
  <ul>
    <li>Don't penalize for backspaces</li>
    <li>Don't allow partial word deletion</li>
    <li>Use provided word lists for content</li>
    <li>Focus on teaching the steno keyboard layout and common words made up of 1 to 3-key chords</li>
  </ul>

  <p>You will break up into groups of 1-6 people. The ability to use steno on your laptop requires you to install Plover, an open source steno engine commissioned by Mirabai. We also recommend people with keyboards that support N Key Rollover to bring them with you. There will be a few keyboards there for you to try out courtesy of Mirabai.</p>

  <h2>About Mirabai</h2>
  <p>Mirabai Knight is a professional realtime stenocaptioner for deaf and hard of hearing students and professionals in New York City. She is certified to produce text at 260 words per minute and is a strategic partner of White Coat Captioning, a realtime firm that specializes in captioning for medical schools and tech conferences. She is also the founder of The Open Steno Project, an open source community that works to make steno technology more accessible to amateurs, hobbyists, and enthusiasts.</p>

  <h2>Raffle Prizes</h2>
  <ul>
    <li><a class="raffle-link" href="https://olkb.com/planck/">A fully assembled plank keyboard</a></li>
    <li><a class="raffle-link" href="https://www.google.com/search?q=stenomod&newwindow=1&tbm=isch&tbo=u&source=univ&sa=X&ved=0ahUKEwiHgMj35tHUAhXMWT4KHe4NB0IQsAQIOQ&biw=582&bih=592">Stenomod Keyboard</a></li>
    <li>T-Shirt Giveaways</li>
  </ul>
</div>

lib/learnathon/web/templates/page/app_block_tickets.html.eex
<div id="tickets" class="block block-inverse block-fill-height app-block-tickets"
     style="background-image: url()"
     id="pricing">
  <div class="block-xs-middle">
    <div class="container">
      <div class="row mb-4">
        <div class="col-lg-5">
          <h1 class="block-title mb-4">
            <span class="text-ribbon">
              <span>Tickets are FREE.</span>
            </span></h1>
            <p class="lead">
            <span class="text-ribbon text-muted">
              <span>
                All we ask is that you enjoy yourself, learn something new and
                share something that you know with someone you meet. 
              </span>
            </span>
            </p>
        </div>
      </div>
      <div class="row">
        <div class="col-xs-12 col-md-6">
          <div class="card accent-primary">
            <div class="card-block">
              <h3 class="card-title">Day One</h3>
              <p class="text-serif mb-1">
              <em>
                Day one is full of talks and we<strike> are currently sold out.</strike>
              </em>
              <strike>We promise to notify everybody if we choose to release more tickets. <a href="#subscribe">Give us your email and you will hear from us when they become available.</a></strike>We have made more tickets available. Enjoy!
              </p>
              <%= render "tickets_day_one.html" %>
            </div>
          </div>
        </div>
        <div class="col-xs-12 col-md-6">
          <div class="card accent-primary">
            <div class="card-block">
              <h3 class="card-title">Day Two</h3>
              <p class="text-serif mb-1">
              <em>
                Day two is a hackathon where you get to use any Webstack to 
                complete the challenges. There are some various themes to 
                choose from.
              </em>
              </p>

              <%= render "tickets_day_two.html" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

lib/learnathon/web/templates/page/footer.html.eex
<div class="block block-inverse block-fill-height accent-primary" id="footer">
  <div class="container">
    <div class="row text-serif">
      <!--
      <div class="col-md-3 mb-4">
        <ul class="list-unstyled list-spaced">
          <li><h4 class="text-center">Speakers</h4></li>
          <li class="text-muted"><em>TBA</em></li>
          <li class="text-muted"><em>Design</em></li>
          <li class="text-muted"><em>Display</em></li>
          <li class="text-muted"><em>Technology</em></li>
        </ul>
      </div>
      -->
      <div class="col-md-6 mb-4">
        <ul class="list-unstyled list-spaced">
          <li><h4 class="text-center">Sponsors</h4></li>
          <li class="text-muted pt-1">
            <img class="w-100" src="images/flatiron-logo.png">
          </li>
          <li class="text-muted pt-3">
            <img class="w-100" src="images/hackerearth.png">
          </li>
          <!--
          <li class="text-muted"><em>Design</em></li>
          <li class="text-muted"><em>Display</em></li>
          <li class="text-muted"><em>Technology</em></li>
          -->
        </ul>
      </div>
      <div class="col-md-6 mb-4">
        <ul class="list-unstyled list-spaced">
          <li><h4 class="text-center">Code of Conduct</h4></li>
          <li class="text-muted text-justify">
            <em>
              Our event is designed to foster meaningful collaboration between 
              participants, community members, and government partners.
              Provide a safe, respectful, and welcoming environment where all 
              are free to fully express their ideas and identities free from 
              discrimination or harassment.
              Collaborate for the purpose of generating ideas that empower, 
              innovate, and develop local impact.
              Presume the value of others and cherish everyone’s ideas, 
              skills, and contributions.
              Encourage others to listen as much as they speak, ask respectful 
              questions, and demystify context.
              Foster an energy that builds “yes, and” ideas, tools, and/or 
              platforms.
            </em>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>

lib/learnathon/web/templates/page/index.html.eex
<div class="stage" id="stage">

  <%= render "app_block_liberty.html" %>
  <%= render "app_block_speakers.html" %>
  <%= render "app_block_schedule.html" %>
  <%= render "app_block_stenohack.html" %>
  <%= render "app_block_flatiron.html" %>
  <%= render "app_block_tickets.html", conn: @conn %>
  <%= render "app_block_stay_up_to_date.html", conn: @conn %>
  <%= render "footer.html" %>
</div>

lib/learnathon/web/templates/page/workshop_form.html.eex
<%= form_for @conn, submission_path(@conn, :create), 
  [as: :submission], fn form -> %>
  <%= text_input form, :name, 
    [class: "form-control", placeholder: "Name"] %>
  <%= text_input form, :company, 
    [class: "form-control", placeholder: "Company"] %>
  <%= email_input form, :email, 
    [class: "form-control", placeholder: "Email"]  %>
  <%= textarea form, :workshop_idea, 
    [class: "form-control", placeholder: "Talk or Workshop Description"]  %>
  <%= text_input form, :time_needed, 
    [class: "form-control", placeholder: "Time Needed (20m - 90m blocks available)"]  %>

  <label id="sponsor" style="color: white;">
    Would you like to be a sponsor?
  </label>

  <div id="sponsorOption" class="form-check">
    <label id="sponsorOptionLabel" class="form-check-label">
    <%= checkbox form, :donation, 
        [
          id: "sponsorOptionInput",
          class: "form-check-input"
        ] %>
        <span class="ml-3">Donation towards food and expenses.</span>
    </label>
  </div>

  <div id="sponsorOption" class="form-check">
    <label id="sponsorOptionLabel" class="form-check-label">
    <%= checkbox form, :prizes, 
        [
          id: "sponsorOptionInput",
          class: "form-check-input"
        ] %>
        <span class="ml-3">
          Prizes and Challenges
        </span>
    </label>
  </div>
  <div id="sponsorOption" class="form-check">
    <label id="sponsorOptionLabel" class="form-check-label">
    <%= checkbox form, :swag, 
        [
          id: "sponsorOptionInput",
          class: "form-check-input"
        ] %>
        <span class="ml-3">
          Donate Swag
        </span>
    </label>
  </div>

  <%= submit "Submit Workshop", [class: "btn btn-primary"] %>
<% end %>

lib/learnathon/web/templates/session/new.html.eex
<article class="login">
<h1>Login</h1>

<%= form_for @conn, session_path(@conn, :create), [as: :session], fn f -> %>
  <div class="form-group">
    <%= text_input f, :email, placeholder: "Email", class: "form-control" %>
  </div>

  <div class="form-group">
    <%= password_input f, :password, placeholder: "Password", 
        class: "form-control" %>
  </div>
  <%= submit "Log in", class: "btn btn-primary btn-lg" %>
<% end %>
</article>